label: "package"
invalidCorreiosTrackingId: "Invalid tracking ID! Correios' tracking IDs are in the following format: `{exampleId}`"
objectNotFoundCorreios: "Object not found in Correios' package database! If it was recently posted, it may take a few hours or days until it is registered in Correios' package database!"
packageUpdate: "Update about `{trackingId}`" #Update about InsertPackageIdHere, the trackingId is a package tracking ID

track:
  label: "track"
  tooManyEventsFiltered: "There are so many package updates that I filtered to show only the latest {maxFilterCount,plural, =0 {# events} one {# event} other {# events}}!"
  description: "View information about a package"
  followPackageUpdates: "Follow Package Updates"
  unfollowPackageUpdates: "Unfollow Package Updates"
  followPackage:
    packageAlreadyDelivered: "This package was already delivered to its recipient!"
    youAreNowFollowingThePackage: "You are now following the package `{trackingId}`! You will receive updates about it in your direct messages, so keep your direct messages open in a server where I'm in! You can check all packages that you are following with {packageListCommandMention}."
    youAreAlreadyFollowingThePackage: "You are already following this package!"
    youAreAlreadyFollowingTooManyPackages: "You are following too many packages!"
  unfollowPackage:
    youUnfollowedThePackage: "You unfollowed the package `{trackingId}`!"
  options:
    trackingId:
      text: "The tracking ID of the package you want to track"

list:
  label: "list"
  description: "View all packages that you are following"
  youAreNotFollowingAnyPackage: "You are not following any packages! You can view a package's status and follow them with {packageTrackCommandMention}."
  followedPackages: "Followed Packages"

  youAreFollowingXPackages: "You are following {packageCount,plural, =0 {# packages} one {# package} other {# packages}}!"
  trackPackage: "Track Package"